services:
  db:
    image: postgres:16.2
    container_name: postgres-db
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: talkzdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112233
  redis:
    image: redis:7
    restart: unless-stopped
    container_name: redis
    networks:
      - backend
    ports:
      - "6380:6379"

volumes:
  db-data:

networks:
  backend:
    driver: bridge
