// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rayhan889/talkz-v2/app/http/controllers"
	"github.com/rayhan889/talkz-v2/app/repositories"
	"github.com/rayhan889/talkz-v2/app/services"
	"github.com/redis/go-redis/v9"
	"gopkg.in/gomail.v2"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB, client *redis.Client, dialer *gomail.Dialer) *App {
	app := NewApp(db, client, dialer)
	return app
}

func InitializeUserRepository(db *gorm.DB) *repositories.UserRepository {
	userRepository := repositories.NewUserRepository(db)
	return userRepository
}

func InitializeBlogRepository(db *gorm.DB) *repositories.BlogRepository {
	blogRepository := repositories.NewBlogRepository(db)
	return blogRepository
}

func InitializeRefreshTokenRepository(db *gorm.DB) *repositories.RefreshTokenRepository {
	refreshTokenRepository := repositories.NewRefreshTokenRepository(db)
	return refreshTokenRepository
}

func InitializeUserService(db *gorm.DB) *services.UserService {
	userRepository := InitializeUserRepository(db)
	userService := services.NewUserService(userRepository)
	return userService
}

func InitializeBlogService(db *gorm.DB, redis2 *redis.Client) *services.BlogService {
	blogRepository := InitializeBlogRepository(db)
	blogService := services.NewBlogService(blogRepository, redis2)
	return blogService
}

func InitializeMailService(dialer *gomail.Dialer) *services.MailService {
	mailService := services.NewMailService(dialer)
	return mailService
}

func InitializeAuthService(db *gorm.DB, dialer *gomail.Dialer) *services.AuthService {
	userService := InitializeUserService(db)
	mailService := InitializeMailService(dialer)
	refreshTokenRepository := InitializeRefreshTokenRepository(db)
	authService := services.NewAuthService(userService, mailService, refreshTokenRepository)
	return authService
}

func InitializeUserController(userService *services.UserService) *controllers.UserController {
	userController := controllers.NewUserController(userService)
	return userController
}

func InitializeBlogController(blogService *services.BlogService) *controllers.BlogController {
	blogController := controllers.NewBlogController(blogService)
	return blogController
}

func InitializeAuthController(authService *services.AuthService) *controllers.AuthController {
	authController := controllers.NewAuthController(authService)
	return authController
}

func InitializeHealthController() *controllers.HealthController {
	healthController := controllers.NewHealthController()
	return healthController
}
