// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rayhan889/talkz-v2/app/http/controllers"
	"github.com/rayhan889/talkz-v2/app/repositories"
	"github.com/rayhan889/talkz-v2/app/services"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB, client *redis.Client) *App {
	app := NewApp(db, client)
	return app
}

func InitializeUserRepository(db *gorm.DB) *repositories.UserRepository {
	userRepository := repositories.NewUserRepository(db)
	return userRepository
}

func InitializeUserService(db *gorm.DB) *services.UserService {
	userRepository := InitializeUserRepository(db)
	userService := services.NewUserService(userRepository)
	return userService
}

func InitializeAuthService(db *gorm.DB) *services.AuthService {
	userService := InitializeUserService(db)
	authService := services.NewAuthService(userService)
	return authService
}

func InitializeUserController(userService *services.UserService) *controllers.UserController {
	userController := controllers.NewUserController(userService)
	return userController
}

func InitializeAuthController(authService *services.AuthService) *controllers.AuthController {
	authController := controllers.NewAuthController(authService)
	return authController
}

func InitializeHealthController() *controllers.HealthController {
	healthController := controllers.NewHealthController()
	return healthController
}
